version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=hotel
      - POSTGRES_DB=hotel_bookings
    command: postgres -c max_locks_per_transaction=128
    ports:
      - 5433:5432
    restart: unless-stopped